"""
Visualises how employment shares across Agriculture, Industry and Services
have shifted in the United States and Germany from 1990 to 2023, using data
loaded into a local SQLite database from the World Bank World Development
Indicators.

The pivot from long to wide format is performed directly in SQL using CASE WHEN
inside SUM, so each sector becomes its own column in the query result. This
avoids the need to reshape the data in Python and keeps the plotting code
simpler.

Indicators used:
    SL.AGR.EMPL.ZS - Employment in agriculture (% of total employment)
    SL.IND.EMPL.ZS - Employment in industry (% of total employment)
    SL.SRV.EMPL.ZS - Employment in services (% of total employment)

Output:
    q5b_sectors.png - Stacked area chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library, no install required
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent sector colours used across both subplots and the shared legend.
sector_colors = {"Agriculture": "green", "Industry": "orange", "Services": "blue"}

# Pivot query using CASE WHEN inside SUM to place each sector's employment share into its own column. 
# For each country and year combination returned by GROUP BY, the CASE WHEN tests whether the sector matches the target. 
# If it does, the employment share is returned; if not, NULL is returned. 
# SUM of a single non-null value alongside NULLs returns that value, effectively placing each sector's share 
# into its own column without needing to reshape the data in Python.
# IS NOT NULL in the WHERE clause excludes rows where the World Bank has no recorded value, 
# as fillna(0) below is only intended to handle structural gaps in the result rather than treating genuinely missing data as zero employment.
q5b = pd.read_sql("""
    SELECT
        iso3,
        year,
        SUM(CASE WHEN sector = 'Agriculture' THEN employment_pct ELSE NULL END) AS Agriculture,
        SUM(CASE WHEN sector = 'Industry'    THEN employment_pct ELSE NULL END) AS Industry,
        SUM(CASE WHEN sector = 'Services'    THEN employment_pct ELSE NULL END) AS Services
    FROM sector_employment
    WHERE iso3 IN ('USA', 'DEU')
        AND employment_pct IS NOT NULL
    GROUP BY iso3, year
    ORDER BY iso3, year
""", conn)

# Two subplots sharing a y-axis so sector shares are directly comparable between the two countries without needing to read different scales.
fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

for ax, (country, group) in zip(axes, q5b.groupby("iso3")):
    # Set year as the index and select sectors in a consistent order so the stack order is identical across both subplots. 
    # fillna(0) handles any year and sector combinations not present in the data to avoid gaps in the stacked areas.
    pivot = group.set_index("year")[["Agriculture", "Industry", "Services"]].fillna(0)
    ax.stackplot(pivot.index,
                 [pivot[s] for s in pivot.columns],
                 labels=pivot.columns,
                 colors=[sector_colors[s] for s in pivot.columns],
                 alpha=0.85)
    ax.set_title(country)
    ax.set_xlabel("Year")
    ax.grid(True, alpha=0.3) # subtle grid to aid readability without cluttering the chart

# Y-axis label only on the leftmost subplot.
axes[0].set_ylabel("Employment Share (%)")

# Single shared legend built manually using Rectangle patches to match the sector_colors mapping, placed outside the subplots to avoid obscuring the chart.
handles = [plt.Rectangle((0, 0), 1, 1, color=sector_colors[s]) for s in ["Agriculture", "Industry", "Services"]]
fig.legend(handles, ["Agriculture", "Industry", "Services"], loc="upper right")
fig.suptitle("Sector Employment Shares Over Time", fontsize=13)

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q5b_sectors.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()