"""
Visualises the year-by-year difference in overall labour force participation
rates between the United States and Germany from 1990 to 2023, using data
loaded into a local SQLite database from the World Bank World Development
Indicators (WDI).

A self-join is used to align both countries on the same year, allowing the
gap to be computed directly in SQL rather than in Python.

Indicator used:
    SL.TLF.CACT.ZS — Labour force participation rate, total (% of population aged 15+)

Output:
    q1b_gap.png — Dual-axis line chart saved to the project graphs directory

Dependencies:
    sqlite3    — standard library
    pandas     — data manipulation and SQL query execution
    matplotlib — chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Self-join on labour_participation using two aliases: us for US rows and de for German rows. 
# Joining on year ensures each output row contains both countries' rates for the same year, allowing the gap to be computed as a single expression in SQL.
# INNER JOIN is used deliberately, if a year is missing for either country, that row is dropped entirely rather than returning a NULL gap that could be 
# misread as zero.
# Germany's filter is placed in the ON clause and the US filter in WHERE, which is the conventional pattern for self-joins in SQL.
# ROUND(..., 2) is applied to all numeric outputs for clean display, though the underlying data remains unchanged in the database.
q1b = pd.read_sql("""
    SELECT
        us.year,
        ROUND(us.rate_total, 2)                 AS us_rate,
        ROUND(de.rate_total, 2)                 AS de_rate,
        ROUND(us.rate_total - de.rate_total, 2) AS gap
    FROM labour_participation AS us
    INNER JOIN labour_participation AS de
        ON us.year = de.year
        AND de.iso3 = 'DEU'
    WHERE us.iso3 = 'USA'
    ORDER BY us.year
""", conn)

# A dual-axis line chart is used here to show both the raw participation rates and the gap on the same figure without the gap line being diminished.
#
# The primary axis (ax) shows the participation rates for both countries. fill_between shades the area between the two lines to make the gap visable
# but with low opacity so the lines remain readable.
#
# The secondary axis (ax2) shows the gap as a dashed grey line, scaled independently so small changes in the gap are visible even when the
# absolute rates are close together.
fig, ax = plt.subplots(figsize=(10, 6))

# Primary axis - participation rates for both countries
ax.plot(q1b["year"], q1b["us_rate"], label="USA",     linewidth=2, color=COLORS["USA"])
ax.plot(q1b["year"], q1b["de_rate"], label="Germany", linewidth=2, color=COLORS["DEU"])

# Shaded region between the two lines to highlight the gap visually
ax.fill_between(q1b["year"], q1b["us_rate"], q1b["de_rate"], alpha=0.1, color="grey")
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")

# Secondary axis - gap between the two countries in percentage points
ax2 = ax.twinx()
ax2.plot(q1b["year"], q1b["gap"], label="Gap (USA - DEU)",
         linewidth=1.5, color="grey", linestyle="--")
ax2.set_ylabel("Gap (percentage points)")
ax2.axhline(0, color="black", linewidth=0.5)

ax.set_title("Participation Rate Gap: USA vs Germany")
ax.set_xlabel("Year")
ax.set_ylabel("Participation Rate (%)")

# Combine legends from both axes into a single legend to avoid duplication
lines1, labels1 = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax.legend(lines1 + lines2, labels1 + labels2, loc="lower left")
ax.grid(True, alpha=0.3)

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q1b_gap.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()