"""
Visualises youth labour force participation rates for the United States and 
Germany across four snapshot years (1995, 2008, 2019, 2023) using data loaded
into a local SQLite database from the World Bank World Development Indicators.

Due to limited World Bank API coverage for broader age bands, only the 15 to 24
age group and its male and female breakdowns are available. The 25 to 54, 55 to
64 and 65 plus indicators returned no data and were excluded from the database.

A pivot is performed in SQL using CASE WHEN inside SUM to extract the
participation rate for each target year into its own column, avoiding the need
to reshape the data in Python after querying.

Indicator used:
    SL.TLF.ACTI.1524.ZS    - Labour force participation rate, ages 15 to 24, total
    SL.TLF.ACTI.1524.MA.ZS - Labour force participation rate, ages 15 to 24, male
    SL.TLF.ACTI.1524.FE.ZS - Labour force participation rate, ages 15 to 24, female

Output:
    q3a_age_pivot.png - Grouped bar chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Pivot query using CASE WHEN inside SUM to extract participation rates for four snapshot years into separate columns. 
# For each country and age group combination returned by GROUP BY, the CASE WHEN tests whether the year matches the target.
# If it does, the participation rate is returned; if not, NULL is returned.
# SUM of a single non-null value alongside NULLs returns that value, effectively placing the rate for each specific year into its own column.
# ELSE NULL is included to make the intent clear when reading the code.
q3a = pd.read_sql("""
    SELECT
        iso3,
        age_group,
        SUM(CASE WHEN year = 1995 THEN participation ELSE NULL END) AS y1995,
        SUM(CASE WHEN year = 2008 THEN participation ELSE NULL END) AS y2008,
        SUM(CASE WHEN year = 2019 THEN participation ELSE NULL END) AS y2019,
        SUM(CASE WHEN year = 2023 THEN participation ELSE NULL END) AS y2023
    FROM age_participation
    WHERE iso3 IN ('USA', 'DEU')
    GROUP BY iso3, age_group
    ORDER BY iso3, age_group
""", conn)

# Target years and their display labels used for the x-axis of each subplot.
# These four years were chosen to capture pre-reform, crisis, recovery and recent periods in the labour market.
years = ["y1995", "y2008", "y2019", "y2023"]
year_labels = ["1995", "2008", "2019", "2023"]

# Extract the unique age groups present in the data to determine how many subplots to create. 
# With the current data this will be 15-24, 15-24 male and 15-24 female.
age_groups = q3a["age_group"].unique()

# One subplot per age group sharing a common y-axis so participation rates are directly comparable across panels.
fig, axes = plt.subplots(1, len(age_groups), figsize=(14, 6), sharey=True)

# When only one age group is present, plt.subplots returns a single Axes object rather than an array.
# Wrapping it in a list ensures the zip loop below works consistently regardless of how many age groups are present.
if len(age_groups) == 1:
    axes = [axes]

# Each subplot shows a grouped bar chart for one age group.
# Two bars per year, one for each country, are offset either side of the tick mark using a calculated offset based on bar width.
for ax, age in zip(axes, age_groups):
    subset = q3a[q3a["age_group"] == age]
    x = range(len(years))
    width = 0.35
    for i, (_, row) in enumerate(subset.iterrows()):
        offset = (i - 0.5) * width
        ax.bar([xi + offset for xi in x], row[years],
               width=width, label=row["iso3"], color=COLORS[row["iso3"]], alpha=0.85)
    ax.set_title(f"Age {age}")
    ax.set_xticks(list(x))
    ax.set_xticklabels(year_labels)
    ax.set_xlabel("Year")
    ax.grid(True, alpha=0.3, axis="y") # horizontal grid lines only to aid bar height comparison

# Y-axis label only on the leftmost subplot since sharey=True links all axes.
axes[0].set_ylabel("Participation Rate (%)")

# Single shared legend built manually using Rectangle patches to match the COLORS mapping, placed outside the subplots to avoid obscuring the bars.
handles = [plt.Rectangle((0, 0), 1, 1, color=COLORS[c]) for c in ["USA", "DEU"]]
fig.legend(handles, ["USA", "Germany"], loc="upper right")
fig.suptitle("Youth Participation Rate by Gender: USA vs Germany", fontsize=13)

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q3a_age_pivot.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()