"""
Visualises overall labour force participation rates for the United States
and Germany from 1990 to 2023 with known economic shocks annotated as
vertical reference lines, allowing the visual impact of each event on
participation trends to be assessed directly from the chart.

A LEFT JOIN is used to attach shock names to the participation data so that
all years are retained in the query result, with shock_name returning NULL
for years where no shock occurred. The shock years are then extracted in
Python to position the vertical annotation lines.

Indicator used:
    SL.TLF.CACT.ZS - Labour force participation rate, total

Output:
    q4a_shocks.png - Annotated line chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and
# Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# LEFT JOIN attaches shock names to matching years in the participation data.
# LEFT JOIN is used rather than INNER JOIN so that all participation rate rows are retained regardless of whether a shock occurred that year. 
# shock_name is NULL for non-shock years and is used only for chart annotations.
q4a = pd.read_sql("""
    SELECT
        lp.iso3,
        lp.year,
        lp.rate_total,
        ls.shock_name
    FROM labour_participation AS lp
    LEFT JOIN labour_shocks AS ls
        ON lp.year = ls.shock_year
    WHERE lp.iso3 IN ('USA', 'DEU')
        AND lp.rate_total IS NOT NULL
    ORDER BY lp.iso3, lp.year
""", conn)

# Extract unique shock year and name pairs for annotation.
# dropna ensures only years with a shock are included in the annotation loop.
shocks = q4a[["year", "shock_name"]].dropna().drop_duplicates()

fig, ax = plt.subplots(figsize=(12, 6))

for country, group in q4a.groupby("iso3"):
    label = "USA" if country == "USA" else "Germany"
    ax.plot(group["year"], group["rate_total"],
            label=label, linewidth=2, color=COLORS[country])

# Vertical dashed lines mark each shock year with a short label rotated to avoid overlapping the participation rate lines.
for _, row in shocks.iterrows():
    ax.axvline(row["year"], color="grey", linewidth=1, linestyle="--", alpha=0.7)
    ax.text(row["year"] + 0.2, ax.get_ylim()[0] + 1, row["shock_name"],
            fontsize=7, color="black", rotation=90, va="bottom")

ax.set_title("Labour Force Participation Rate with Economic Shocks Annotated")
ax.set_xlabel("Year")
ax.set_ylabel("Participation Rate (%)")
ax.legend()
ax.grid(True, alpha=0.3)  # subtle grid to aid readability without cluttering the chart

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q4a_shocks.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()
