"""
Visualises male and female labour force participation rates for the United
States and Germany from 1990 to 2023, and how the gender gap has evolved
over time in each country.

Two subplots are used: the first shows male and female rates on the same
axes for both countries so the absolute levels and gap are visible together.
The second shows the gender gap (male minus female) as a single line per
country, making it easier to compare how the gap has narrowed or widened.

The gender_gap column is a computed column in the database defined as
rate_male minus rate_female, so it does not need to be recalculated in Python.

Indicator used:
    SL.TLF.CACT.MA.ZS - Labour force participation rate, male
    SL.TLF.CACT.FE.ZS - Labour force participation rate, female

Output:
    q2a_gender_rates.png - Dual-panel line chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Selects male and female participation rates and the precomputed gender_gap column for both countries. 
# Both rate_male and rate_female must be non-null to ensure gender_gap is meaningful and no incomplete rows are plotted.
# Ordered by country then year for consistent groupby behaviour when plotting.
q2a = pd.read_sql("""
    SELECT
        iso3,
        year,
        rate_male,
        rate_female,
        gender_gap
    FROM labour_participation
    WHERE iso3 IN ('USA', 'DEU')
        AND rate_male IS NOT NULL
        AND rate_female IS NOT NULL
    ORDER BY iso3, year
""", conn)

# Two subplots stacked vertically sharing a common x-axis.
# The top panel shows male and female rates for both countries to communicate absolute levels. 
# The bottom panel shows the gender gap as a single line per country to make the trend in the gap easier to read independently of the absolute rate levels.
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 9), sharex=True)

for country, group in q2a.groupby("iso3"):
    color = COLORS[country]
    label = "USA" if country == "USA" else "Germany"

    # Male rates plotted as solid lines, female as dashed, 
    # so both countries can be shown on the same axes without relying on colour to distinguish male from female.
    ax1.plot(group["year"], group["rate_male"],
             label=f"{label} male", linewidth=2, color=color, linestyle="solid")
    ax1.plot(group["year"], group["rate_female"],
             label=f"{label} female", linewidth=2, color=color, linestyle="dashed")

ax1.set_title("Male and Female Labour Force Participation Rates: USA vs Germany")
ax1.set_ylabel("Participation Rate (%)")
ax1.legend(loc="lower left")
ax1.grid(True, alpha=0.3)  # subtle grid to aid readability without cluttering the chart

for country, group in q2a.groupby("iso3"):
    label = "USA" if country == "USA" else "Germany"
    ax2.plot(group["year"], group["gender_gap"],
             label=label, linewidth=2, color=COLORS[country])

ax2.set_title("Gender Gap in Participation Rate (Male minus Female)")
ax2.set_xlabel("Year")
ax2.set_ylabel("Gender Gap (percentage points)")
ax2.legend(loc="upper right")
ax2.grid(True, alpha=0.3)

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q2a_gender_rates.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()
