'''
Visualises overall labour force participation rates for the United States 
and Germany from 1990 to 2023 using data loaded into a local SQLite database
from the World Bank World Development Indicators (WDI).

Indicator used:
    SL.TLF.CACT.ZS - Labour force participation rate, total (% of population aged 15+)

Output:
    q1a_participation.png - Line chart saved to the project graphs directory

Dependencies:
    sqlite3   - standard library
    pandas    - data manipulation and SQL query execution
    matplotlib - chart rendering
'''

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Selects the total participation rate for the US (USA) and Germany (DEU).
# The IS NOT NULL excludes years where the World Bank has no recorded value, as NULL in SQL is not equivalent to zero and would produce blank rows.
# Results are ordered by country then year for consistent groupby behaviour when plotting.
q1a = pd.read_sql("""
    SELECT
        iso3,
        year,
        rate_total
    FROM labour_participation
    WHERE iso3 IN ('USA', 'DEU')
        AND rate_total IS NOT NULL
    ORDER BY iso3, year;
""", conn)

# A line chart is appropriate here as both variables are continuous, and the goal is to show trend over time for the two countries simultaneously.
# groupby("iso3") splits the dataframe into one group per country, so each country gets its own line without needing to filter the dataframe manually.
# This also means the loop would handle additional countries automatically if the query were extended.
fig, ax = plt.subplots(figsize=(10, 6))
for country, group in q1a.groupby("iso3"):
    ax.plot(group["year"], group["rate_total"],
            label=country, linewidth=2, color=COLORS[country])

ax.set_title("Labour Force Participation Rate: USA vs Germany (1990-2023)")
ax.set_xlabel("Year")
ax.set_ylabel("Participation Rate (%)")
ax.legend()
ax.grid(True, alpha=0.3) # subtle grid to aid readability without cluttering the chart

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q1a_participation.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()
