"""
Visualises the difference in gender gaps between the United States and
Germany from 1990 to 2023, showing whether the two countries are converging
or diverging in terms of how equally men and women participate in the
labour force.

A self-join is used to align both countries on the same year, allowing the
difference in gender gaps to be computed directly in SQL. A positive value
means the US gender gap exceeds Germany's, and a negative value means
Germany's gap is larger.

The gender_gap column is a computed column in the database defined as
rate_male minus rate_female, so it does not need to be recalculated in Python.

Indicator used:
    SL.TLF.CACT.MA.ZS - Labour force participation rate, male
    SL.TLF.CACT.FE.ZS - Labour force participation rate, female

Output:
    q2b_gender_gap_diff.png - Line chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Self-join on labour_participation using two aliases: us for US rows and de for German rows. 
# Joining on year ensures each output row contains both countries gender gaps for the same year.
# INNER JOIN is used deliberately so that if a year is missing for either country, that row is dropped entirely rather than returning a NULL difference.
# Germany's filter is placed in the ON clause and the US filter in WHERE.
# Both gender_gap values must be non-null to ensure the difference is meaningful.
q2b = pd.read_sql("""
    SELECT
        us.year,
        ROUND(us.gender_gap, 2)                 AS us_gap,
        ROUND(de.gender_gap, 2)                 AS de_gap,
        ROUND(us.gender_gap - de.gender_gap, 2) AS gap_difference
    FROM labour_participation AS us
    INNER JOIN labour_participation AS de
        ON us.year = de.year
        AND de.iso3 = 'DEU'
    WHERE us.iso3 = 'USA'
        AND us.gender_gap IS NOT NULL
        AND de.gender_gap IS NOT NULL
    ORDER BY us.year
""", conn)

fig, ax = plt.subplots(figsize=(11, 5))

# Single line showing the difference between the two countries gender gaps over time.
ax.plot(q2b["year"], q2b["gap_difference"], linewidth=2, color="grey")

# Reference line at zero marks the point where both countries gaps are equal.
# Values above zero mean the US gender gap exceeds Germany's; values below mean Germany's gap is larger.
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")

# Shaded regions make the direction of the difference immediately readable without needing to check the axis. 
# Blue shading indicates years where the US gender gap is larger; red where Germany's is larger.
ax.fill_between(q2b["year"], q2b["gap_difference"], 0,
                where=(q2b["gap_difference"] >= 0), alpha=0.15, color=COLORS["USA"],
                label="USA gap larger")
ax.fill_between(q2b["year"], q2b["gap_difference"], 0,
                where=(q2b["gap_difference"] < 0), alpha=0.15, color=COLORS["DEU"],
                label="Germany gap larger")

ax.set_title("Difference in Gender Gap (USA minus Germany)")
ax.set_xlabel("Year")
ax.set_ylabel("Difference (percentage points)")
ax.legend()
ax.grid(True, alpha=0.3)  # subtle grid to aid readability without cluttering the chart

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q2b_gender_gap_diff.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()
