"""
Performs a data quality check on the sector_employment table by verifying
that the three sector employment shares (Agriculture, Industry and Services)
sum to 100 percent for every country and year combination.

If the data is consistent, all values should lie on or very close
to the green reference line at 100. Any deviation would indicate missing
sectors.

This check is run before any analytical queries on sector employment to ensure
the data is valid before drawing conclusions from it.

Indicators used:
    SL.AGR.EMPL.ZS - Employment in agriculture (% of total employment)
    SL.IND.EMPL.ZS - Employment in industry (% of total employment)
    SL.SRV.EMPL.ZS - Employment in services (% of total employment)

Output:
    q5a_quality.png - Line chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library, no install required
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Aggregates the three sector shares for each country and year using SUM and GROUP BY. 
# ROUND(..., 1) is applied to smooth out minor floating point differences in the source data. 
# The result should be 100.0 for every row if the data is complete and consistent.
q5a = pd.read_sql("""
    SELECT
        iso3,
        year,
        ROUND(SUM(employment_pct), 1) AS total_pct
    FROM sector_employment
    WHERE iso3 IN ('USA', 'DEU')
    GROUP BY iso3, year
    ORDER BY iso3, year
""", conn)

fig, ax = plt.subplots(figsize=(10, 4))

# One line per country showing the sum of sector shares over time.
# groupby("iso3") splits the dataframe into one group per country so each gets its own line without needing to filter manually.
for country, group in q5a.groupby("iso3"):
    ax.plot(group["year"], group["total_pct"],
            label=country, linewidth=2, color=COLORS[country])
    
# Reference line at 100 representing the expected sum of all sector shares.
# If all lines lie on this reference, the data passes the quality check.    
ax.axhline(100, color="green", linestyle="--", linewidth=1, label="Expected = 100")

ax.set_title("Sector Employment Data Quality Check")
ax.set_xlabel("Year")
ax.set_ylabel("Sum of Sector Shares (%)")
ax.legend()
ax.grid(True, alpha=0.3) # subtle grid to aid readability without cluttering the chart

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q5a_quality.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()