"""
Visualises the difference in sector employment shares between the United
States and Germany in 2023, showing which country has a higher share of
employment in Agriculture, Industry and Services.

A self-join is used to align both countries on the same year and sector,
allowing the difference to be computed directly in SQL. INNER JOIN is used
deliberately so that if either country is missing a sector in 2023, that
row is dropped entirely rather than returning a NULL difference.

The year 2023 is hardcoded in this query as the analysis is specifically
focused on the most recent snapshot.

Indicators used:
    SL.AGR.EMPL.ZS - Employment in agriculture (% of total employment)
    SL.IND.EMPL.ZS - Employment in industry (% of total employment)
    SL.SRV.EMPL.ZS - Employment in services (% of total employment)

Output:
    q5c_sector_diff.png - Horizontal bar chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Self-join on sector_employment using two aliases: a for US rows and b for German rows. 
# Joining on both year and sector ensures rows are only paired when they represent the same year and the same sector.
# INNER JOIN is used deliberately so that if either country is missing a sector in 2023, that row is dropped entirely rather than returning a NULL difference
# that could distort the chart.
# Germany's filter is placed in the ON clause and the US filter in WHERE.
# ROUND(..., 2) is applied to all numeric outputs for clean display, though the underlying data remains unchanged in the database.
# ORDER BY difference DESC means sectors where the US leads appear at the top of the chart and sectors where Germany leads appear at the bottom.
q5c = pd.read_sql("""
    SELECT
        a.sector,
        ROUND(a.employment_pct, 2)                   AS us_pct,
        ROUND(b.employment_pct, 2)                   AS de_pct,
        ROUND(a.employment_pct - b.employment_pct, 2) AS difference
    FROM sector_employment AS a
    INNER JOIN sector_employment AS b
        ON a.year = b.year
        AND a.sector = b.sector
        AND b.iso3 = 'DEU'
    WHERE a.iso3 = 'USA'
        AND a.year = 2023
    ORDER BY difference DESC
""", conn)

fig, ax = plt.subplots(figsize=(8, 4))

# Bars are coloured conditionally: blue where the US share exceeds Germany's and red where Germany leads, making the direction of the difference
# immediately readable without needing to check the axis.
colors = ["blue" if d >= 0 else "red" for d in q5c["difference"]]

ax.barh(q5c["sector"], q5c["difference"], color=colors, alpha=0.85)

# Vertical reference line at zero to clearly separate positive and negative differences.
ax.axvline(0, color="black", linewidth=0.8)
ax.set_title("Sector Employment Difference in 2023\nUSA minus Germany (percentage points)")
ax.set_xlabel("Difference (percentage points)")
ax.grid(True, alpha=0.3, axis="x") # vertical grid lines only to aid bar length comparison

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q5c_sector_diff.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()