"""
Visualises the year-on-year change in labour force participation rates for
the United States and Germany from 1990 to 2023, with known economic shocks
annotated to show which drops coincide with major events such as the 2008
Global Financial Crisis and the COVID-19 pandemic.

A self-join on consecutive years computes the change from one year to the
next directly in SQL. A LEFT JOIN then attaches shock names so all years are retained in the result
regardless of whether a shock occurred.

A bar chart is used rather than a line chart as year-on-year change is a discrete measure.

Indicator used:
    SL.TLF.CACT.ZS - Labour force participation rate, total

Output:
    q4b_yoy_change.png - Annotated bar chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Consistent colour scheme used across all question scripts so that USA and Germany are always represented by the same colour in every chart.
COLORS = {"USA": "blue", "DEU": "red"}

# Self-join on consecutive years: curr is the current year and prev is the prior year, joined on the condition that curr.year = prev.year + 1.
# This computes the year-on-year change without needing to shift the column in Python. 
# INNER JOIN on consecutive years means the first year of data is excluded as there is no prior year to compare against.
# LEFT JOIN on labour_shocks retains all participation rows, with shock_name returning NULL for non-shock years.
q4b = pd.read_sql("""
    SELECT
        curr.iso3,
        curr.year,
        ROUND(curr.rate_total, 2)                   AS rate,
        ROUND(curr.rate_total - prev.rate_total, 2) AS yoy_change,
        ls.shock_name
    FROM labour_participation AS curr
    INNER JOIN labour_participation AS prev
        ON curr.iso3 = prev.iso3
        AND curr.year = prev.year + 1
    LEFT JOIN labour_shocks AS ls
        ON curr.year = ls.shock_year
    WHERE curr.iso3 IN ('USA', 'DEU')
        AND curr.rate_total IS NOT NULL
        AND prev.rate_total IS NOT NULL
    ORDER BY curr.iso3, curr.year
""", conn)

# Extract unique shock year and name pairs for annotation.
shocks = q4b[["year", "shock_name"]].dropna().drop_duplicates()

# One subplot per country sharing a common y-axis so year-on-year changes are directly comparable in scale between the two countries.
fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

for ax, (country, group) in zip(axes, q4b.groupby("iso3")):
    label = "USA" if country == "USA" else "Germany"

    # Bars are coloured conditionally: the country colour for positive changes and grey for negative changes, making drops immediately visible.
    bar_colors = [COLORS[country] if v >= 0 else "grey" for v in group["yoy_change"]]
    ax.bar(group["year"], group["yoy_change"], color=bar_colors, alpha=0.8, width=0.8)

    # Vertical dashed lines mark each shock year with a short rotated label.
    for _, row in shocks.iterrows():
        ax.axvline(row["year"], color="grey", linewidth=1, linestyle="--", alpha=0.7)
        ax.text(row["year"] + 0.2, ax.get_ylim()[0], row["shock_name"],
                fontsize=7, color="black", rotation=90, va="bottom")

    # Reference line at zero to clearly separate positive and negative changes.
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(label)
    ax.set_xlabel("Year")
    ax.grid(True, alpha=0.3, axis="y")  # horizontal grid lines only to aid bar height comparison

axes[0].set_ylabel("Year-on-Year Change (percentage points)")
fig.suptitle("Year-on-Year Change in Labour Force Participation Rate with Economic Shocks", fontsize=13)

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q4b_yoy_change.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()
