"""
Visualises the difference in youth labour force participation rates between
the United States and Germany for the most recent year available in the
database, broken down by age group and gender.

A self-join is used to align both countries on the same year and age group,
allowing the difference to be computed directly in SQL. The chart is filtered
to the most recent year dynamically rather than hardcoding a year, so it
remains correct if the database is updated with newer data - not neccessary in the
context of the project but an interesting extension for further research.

Indicator used:
    SL.TLF.ACTI.1524.ZS    - Labour force participation rate, ages 15 to 24, total
    SL.TLF.ACTI.1524.MA.ZS - Labour force participation rate, ages 15 to 24, male
    SL.TLF.ACTI.1524.FE.ZS - Labour force participation rate, ages 15 to 24, female

Output:
    q3b_age_diff.png -  Horizontal bar chart saved to the project graphs directory

Dependencies:
    sqlite3    - standard library
    pandas     - data manipulation and SQL query execution
    matplotlib - chart rendering
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connects to the local SQLite database containing the cleaned and loaded World Bank labour market data. 
# The database is generated by fetch_worldbank.py and schema.sql before this script is run.
conn = sqlite3.connect("labour_market.db")

# Self-join on age_participation using two aliases: a for US rows and b for German rows. 
# Joining on both year and age_group ensures rows are only paired when they represent the same year and the same age group.
# INNER JOIN is used deliberately so that if either country is missing a rate for a particular age group or year, that row is dropped entirely rather than
# returning a NULL difference that could be misread as zero.
# Germany's filter is placed in the ON clause and the US filter in WHERE, which is the conventional pattern for self-joins in SQL.
# ROUND(..., 2) is applied to all numeric outputs for clean display, though the underlying data remains unchanged in the database.
q3b = pd.read_sql("""
    SELECT
        a.year,
        a.age_group,
        ROUND(a.participation, 2)                   AS us_rate,
        ROUND(b.participation, 2)                   AS de_rate,
        ROUND(a.participation - b.participation, 2) AS difference
    FROM age_participation AS a
    INNER JOIN age_participation AS b
        ON a.year = b.year
        AND a.age_group = b.age_group
        AND b.iso3 = 'DEU'
    WHERE a.iso3 = 'USA'
    ORDER BY difference DESC
""", conn)

# Plot for most recent year available
latest_year = q3b["year"].max()
subset = q3b[q3b["year"] == latest_year].sort_values("difference")

fig, ax = plt.subplots(figsize=(8, 5))

# Bars are coloured conditionally: blue where the US rate exceeds Germany's and red where Germany leads, 
# making the direction of the difference immediately readable without needing to check the axis.
colors = ["red" if d < 0 else "blue" for d in subset["difference"]]

ax.barh(subset["age_group"], subset["difference"], color=colors, alpha=0.85)

# Vertical reference line at zero to clearly separate positive and negative differences.
ax.axvline(0, color="black", linewidth=0.8)

# Title includes the latest year 
ax.set_title(f"Participation Rate Difference by Age Group ({latest_year})\nUSA minus Germany")
ax.set_xlabel("Difference (percentage points)")
ax.set_ylabel("Age Group")
ax.grid(True, alpha=0.3, axis="x") # vertical grid lines only to aid bar length comparison

# Saves the figure as a PNG at 150 dpi to maximise usability
plt.tight_layout()
plt.savefig("/Users/cameronbahlmann/git-projects/ds-sql-project-1/analysis/graphs/q3b_age_diff.png", dpi=150)
plt.show()

# Explicitly close the connection as good practice
conn.close()